# Generated by Django 6.1.1 on 2026-10-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Completed'), ('failed', 'Failed')], default='running', max_length=10)),
                ('params', models.JSONField(default=dict)),
                ('command', models.TextField(blank=True)),
                ('output_prefix', models.CharField(max_length=255)),
                ('log', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('summary', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
